-- Generated by Oracle SQL Developer Data Modeler 4.0.0.825
--   at:        2014-04-13 21:15:13 CEST
--   site:      SQL Server 2008
--   type:      SQL Server 2008




DROP
  TABLE BazarTires
GO

DROP
  TABLE CarFleet
GO

DROP
  TABLE Contract
GO

ALTER TABLE BazarTires
DROP
  CONSTRAINT BazarTires_Customers_FK
GO
ALTER TABLE CarFleet
DROP
  CONSTRAINT CarFleet_Customers_FK
GO
ALTER TABLE Contract
DROP
  CONSTRAINT FK_ASS_2
GO
ALTER TABLE "Order"
DROP
  CONSTRAINT Order_Customers_FK
GO
ALTER TABLE StoredWheelsDescription
DROP
  CONSTRAINT StoredWheelsDescription_Customers_FK
GO
DROP
  TABLE Customers
GO

DROP
  TABLE EmployeeAttendance
GO

ALTER TABLE EmployeeAttendance
DROP
  CONSTRAINT EmployeeAttendance_Employees_FK
GO
ALTER TABLE Contract
DROP
  CONSTRAINT FK_ASS_3
GO
ALTER TABLE "Order"
DROP
  CONSTRAINT Order_Employees_FK
GO
ALTER TABLE StoredWheelsDescription
DROP
  CONSTRAINT StoredWheelsDescription_Employees_FK
GO
ALTER TABLE StoredWheelsDescription
DROP
  CONSTRAINT StoredWheelsDescription_Employees_FKv1
GO
DROP
  TABLE Employees
GO

ALTER TABLE OrderSuplierTiresOKPneu
DROP
  CONSTRAINT FK_ASS_10
GO
DROP TABLE "Order"
GO

DROP
  TABLE OrderSuplierTiresOKPneu
GO

DROP
  TABLE PriceHistory
GO

DROP
  TABLE StoredWheelsDescription
GO

ALTER TABLE PriceHistory
DROP
  CONSTRAINT PriceHistory_SuplierTiresOKpneu_FK
GO
ALTER TABLE OrderSuplierTiresOKPneu
DROP
  CONSTRAINT FK_ASS_9
GO
DROP
  TABLE SuplierTiresOKpneu
GO

CREATE
  TABLE BazarTires
  (
    Id           INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Manufacturer VARCHAR (10) NOT NULL ,
    Size         INTEGER NOT NULL ,
    Type         VARCHAR (50) NOT NULL ,
    Description  VARCHAR (200) ,
    Customers_id INTEGER NOT NULL ,
    CONSTRAINT BazarTires_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE CarFleet
  (
    CarIdentityNumber        VARCHAR (7) NOT NULL ,
    WinterWheelsSize         INTEGER NOT NULL ,
    SummerWheelSize          INTEGER NOT NULL ,
    CarManufacturer          VARCHAR (20) ,
    CarType                  VARCHAR (40) ,
    PreferedTyreManufacturer VARCHAR (10) ,
    TreadDepthWinter         TINYINT ,
    TreadDepthSummer         TINYINT ,
    Customers_id             INTEGER NOT NULL ,
    CONSTRAINT CarFleet_PK PRIMARY KEY CLUSTERED (CarIdentityNumber)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Contract
  (
    id              INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Customers_id    INTEGER NOT NULL ,
    Employees_id    INTEGER NOT NULL ,
    CustomerArrival DATETIME NOT NULL ,
    GarageNumber    SMALLINT NOT NULL ,
    CustomerExit    DATETIME ,
    Payment         INTEGER ,
    VAT BIT ,
    CONSTRAINT Contract__IDX PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Customers
  (
    id         INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    email      VARCHAR (50) NOT NULL ,
    fname      VARCHAR (20) NOT NULL ,
    lname      VARCHAR (20) NOT NULL ,
    phone      VARCHAR (15) NOT NULL ,
    adress     VARCHAR (20) NOT NULL ,
    city       VARCHAR (20) NOT NULL ,
    postalCode INTEGER NOT NULL ,
    CONSTRAINT Customers_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE EmployeeAttendance
  (
    Id      INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Arrival DATETIME NOT NULL ,
    "Exit"  DATETIME ,
    Wage MONEY ,
    Paid BIT NOT NULL ,
    Employees_id INTEGER NOT NULL ,
    CONSTRAINT EmployeeAttendance_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Employees
  (
    id         INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    login      VARCHAR (10) NOT NULL ,
    Fname      VARCHAR (20) NOT NULL ,
    Lname      VARCHAR (20) NOT NULL ,
    Password   VARCHAR (20) NOT NULL ,
    Phone      VARCHAR (15) NOT NULL ,
    Adress     VARCHAR (20) NOT NULL ,
    City       VARCHAR (20) NOT NULL ,
    Experience TINYINT NOT NULL ,
    BirthDate  DATE NOT NULL ,
    CONSTRAINT Employees_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE "Order"
  (
    Id           INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Customers_id INTEGER NOT NULL ,
    Employees_id INTEGER NOT NULL ,
                 DATETIME DATETIME NOT NULL ,
    status       CHAR (1) NOT NULL ,
    CONSTRAINT Order_PK PRIMARY KEY CLUSTERED (Id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE OrderSuplierTiresOKPneu
  (
    SuplierTiresOKpneu_EAN VARCHAR (14) NOT NULL ,
    Order_Id               INTEGER NOT NULL ,
    ProductCount           INTEGER NOT NULL ,
    PricePerPiece MONEY NOT NULL ,
    CONSTRAINT OrderSuplierTiresOKPneu__IDX PRIMARY KEY CLUSTERED (
    SuplierTiresOKpneu_EAN)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE PriceHistory
  (
    id INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    oldPrice MONEY NOT NULL ,
                           DATE DATE NOT NULL ,
    SuplierTiresOKpneu_EAN VARCHAR (14) NOT NULL ,
    CONSTRAINT PriceHistory_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE StoredWheelsDescription
  (
    id                   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Tiremanufacturer     VARCHAR (10) NOT NULL ,
    DiscDescription      VARCHAR (50) ,
    TireDecription       VARCHAR (50) NOT NULL ,
    StoreDate            DATETIME NOT NULL ,
    UnstoreDate          DATETIME ,
    Customers_id         INTEGER NOT NULL ,
    Employees_id_Store   INTEGER NOT NULL ,
    Employees_id_Unstore INTEGER NOT NULL ,
    CONSTRAINT StoredWheelsDescription_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE SuplierTiresOKpneu
  (
    EAN                VARCHAR (14) NOT NULL ,
    Manufacturer       VARCHAR (10) NOT NULL ,
    Size               INTEGER NOT NULL ,
    Name               VARCHAR (50) NOT NULL ,
    ExternalStore      INTEGER NOT NULL ,
    code               VARCHAR (15) ,
    PhotoUrl_UrlId     INTEGER NOT NULL ,
    Description_DescId INTEGER NOT NULL ,
    OnStore            INTEGER NOT NULL ,
    Price MONEY NOT NULL ,
    Season      CHAR (1) ,
    Description VARCHAR (2000) ,
    Photo       VARCHAR (200) ,
    CONSTRAINT SuplierTiresOKpneu_PK PRIMARY KEY CLUSTERED (EAN)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

ALTER TABLE BazarTires
ADD CONSTRAINT BazarTires_Customers_FK FOREIGN KEY
(
Customers_id
)
REFERENCES Customers
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE CarFleet
ADD CONSTRAINT CarFleet_Customers_FK FOREIGN KEY
(
Customers_id
)
REFERENCES Customers
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE EmployeeAttendance
ADD CONSTRAINT EmployeeAttendance_Employees_FK FOREIGN KEY
(
Employees_id
)
REFERENCES Employees
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE OrderSuplierTiresOKPneu
ADD CONSTRAINT FK_ASS_10 FOREIGN KEY
(
Order_Id
)
REFERENCES "Order"
(
Id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Contract
ADD CONSTRAINT FK_ASS_2 FOREIGN KEY
(
Customers_id
)
REFERENCES Customers
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Contract
ADD CONSTRAINT FK_ASS_3 FOREIGN KEY
(
Employees_id
)
REFERENCES Employees
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE OrderSuplierTiresOKPneu
ADD CONSTRAINT FK_ASS_9 FOREIGN KEY
(
SuplierTiresOKpneu_EAN
)
REFERENCES SuplierTiresOKpneu
(
EAN
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE "Order"
ADD CONSTRAINT Order_Customers_FK FOREIGN KEY
(
Customers_id
)
REFERENCES Customers
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE "Order"
ADD CONSTRAINT Order_Employees_FK FOREIGN KEY
(
Employees_id
)
REFERENCES Employees
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE PriceHistory
ADD CONSTRAINT PriceHistory_SuplierTiresOKpneu_FK FOREIGN KEY
(
SuplierTiresOKpneu_EAN
)
REFERENCES SuplierTiresOKpneu
(
EAN
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE StoredWheelsDescription
ADD CONSTRAINT StoredWheelsDescription_Customers_FK FOREIGN KEY
(
Customers_id
)
REFERENCES Customers
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE StoredWheelsDescription
ADD CONSTRAINT StoredWheelsDescription_Employees_FK FOREIGN KEY
(
Employees_id_Store
)
REFERENCES Employees
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE StoredWheelsDescription
ADD CONSTRAINT StoredWheelsDescription_Employees_FKv1 FOREIGN KEY
(
Employees_id_Unstore
)
REFERENCES Employees
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
